spring:
  application:
    name: redis-examples


redis:
  config:
    username: my-client
    password: wrong-password
    timeout: PT10S  # 10 seconds
    ttl: PT15M      # 15 minutes
    nodes:
      - localhost:7001
      - localhost:7002
      - localhost:7003
      - localhost:7004
      - localhost:7005
      - localhost:7006
    maxTotalPool: 8
    maxIdlePool: 4
    minIdlePool: 2