spring:
  application:
    name: redis-examples


redis:
  config:
    master: mymaster
    sentinel-password: my-sentinel-password
    username: my-client
    password: my-password1
    timeout: PT10S  # 10 seconds
    ttl: PT15M      # 15 minutes
    nodes:
      - sentinel-1:26379
      - sentinel-2:26379
      - sentinel-3:26379
    maxTotalPool: 8
    maxIdlePool: 4
    minIdlePool: 2