spring:
  application:
    name: redis-examples


redis:
  config:
    master: mymaster
    sentinel-username: sentinel-username
    sentinel-password: wrong-sentinel-password
    username: my-client
    password: my-password1
    timeout: PT10S  # 10 seconds
    ttl: PT15M      # 15 minutes
    nodes:
      - localhost:26379
      - localhost:26380
      - localhost:26381
    maxTotalPool: 8
    maxIdlePool: 4
    minIdlePool: 2